from __future__ import annotations

from typing import Any
from typing import Callable
from typing import Awaitable
from typing import AsyncIterator
from typing import AsyncContextManager
from typing import Protocol


class AsyncCursor(Protocol):
    rowcount: int

    async def execute(self, query: Any, params: Any = ...) -> None: ...
    async def executemany(self, query: Any, params_seq: Any) -> None: ...
    async def fetchone(self) -> Any: ...
    async def fetchall(self) -> list[Any]: ...


class AsyncConnection(AsyncContextManager["AsyncConnection"], Protocol):
    async def execute(self, query: Any, params: Any = ...) -> Any: ...
    def cursor(self, **kwargs: Any) -> AsyncContextManager[AsyncCursor]: ...
    def transaction(self) -> AsyncContextManager[None]: ...
    def notifies(self) -> AsyncIterator[Any]: ...
    async def close(self) -> None: ...


Connect = Callable[[], Awaitable[AsyncConnection]]
